---
kind: pipeline
type: docker
name: pull-request

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: without-increment
    image: python:3
    commands:
      - python main.py
      - cat semver
      # Sleep 1 second to ensure the output of cat is displayed
      - sleep 1
    settings:
      file: "CHANGELOG.example.md"
      autoincrement: false
  - name: with-major-increment
    image: python:3
    commands:
      - export DRONE_SEMVER=1.0.1
      - python main.py
      - cat semver
      # Sleep 1 second to ensure the output of cat is displayed
      - sleep 1
    settings:
      file: "CHANGELOG.example.md"
      autoincrement: true
