---
kind: pipeline
type: docker
name: pull-request

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: with-initial-version
    image: python:3
    commands:
      - unset DRONE_SEMVER
      - python main.py
      - python ci/validator.py 1.0.0
    settings:
      file: "examples/Major.md"
      autoincrement: false
  - name: with-major-update
    image: python:3
    commands:
      - export DRONE_SEMVER=1.0.1
      - python main.py
      - python ci/validator.py 2.0.0
    settings:
      file: "examples/Major.md"
      autoincrement: true
  - name: with-minor-update
    image: python:3
    commands:
      - export DRONE_SEMVER=1.0.1
      - python main.py
      - python ci/validator.py 1.1.0
    settings:
      file: "examples/Minor.md"
      autoincrement: true
  - name: with-patch-update
    image: python:3
    commands:
      - export DRONE_SEMVER=1.0.1
      - python main.py
      - python ci/validator.py 1.0.2
    settings:
      file: "examples/Patch.md"
      autoincrement: true
  - name: docker-build
    image: plugins/docker
    commands:
      - echo $TEST
    settings:
      repo: cedrichopf/drone-semver
      dry_run: true
    environment:
      TEST: cat semver
